.TH "custodia" "7" "2015" "Custoia" "Custodia Secrets Manager"
.SH "NAME"
cutodia
.SH "DESCRIPTION"
Custodia is a omdular and pluggable Secrets Manager.
It allows to serve retrieve, manage and store secrets for other applications.
It is useful for distributed, stateless applications that use an image file
base approach for instantiation like container based images.
But it is alaso useful to manage distribution of key material across a
multiple machines over a network.
