.TH "custodia" "7" "2015" "Custodia" "Custodia Secrets Manager"
.SH "NAME"
custodia
.SH "DESCRIPTION"
Custodia is a modular and pluggable Secrets Manager.
It allows to serve retrieve, manage and store secrets for other applications.
It is useful for distributed, stateless applications that use an image file
base approach for instantiation like container based images.
But it is also useful to manage distribution of key material across a
multiple machines over a network.
